---
- name: Setup my workstation
  hosts: localhost
  connection: local
  become: true

  vars_files:
    - vars/main.yml

  handlers:
    - name: Reload /etc/profile
      ansible.builtin.import_tasks: handlers/main.yml

  pre_tasks:
    - name: Update package caches if required (Debian)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Update package caches if required (RedHat)
      ansible.builtin.yum:
        update_cache: true
      when: ansible_os_family == "RedHat"

  tasks:
    - name: Debug download_dir
      ansible.builtin.debug:
        msg: "{{ download_dir }}"

    - name: Install tools
      ansible.builtin.include_tasks:
        file: tasks/install-tools.yml

    - name: Install AWS CLI v2
      ansible.builtin.include_tasks:
        file: tasks/awscli.yml

    - name: Install Go
      ansible.builtin.include_tasks:
        file: tasks/go.yml
      ignore_errors: true

    - name: Install Terraform
      ansible.builtin.include_tasks:
        file: tasks/terraform.yml

    - name: Install NodeJS
      ansible.builtin.include_tasks:
        file: tasks/nodejs.yml
      when: ansible_os_family == "Debian"

    - name: Configure Git
      ansible.builtin.include_tasks:
        file: tasks/git.yml

    - name: Configure SSH for GitHub
      ansible.builtin.include_tasks:
        file: tasks/ssh.yml

    - name: Print SSH key
      ansible.builtin.debug:
        msg: "{{ ssh_key_pub }}"
      become: false
