---
- name: Setup my workstation
  hosts: localhost
  connection: local
  become: true

  vars_files:
    - vars/main.yml

  handlers:
    - name: Reload /etc/profile
      ansible.builtin.import_tasks: handlers/main.yml

  pre_tasks:

    - name: End play if the system is not Debian
      ansible.builtin.meta: end_play
      when: ansible_facts['os_family'] != 'Debian'

    - name: Update package caches if required
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

  tasks:
    - name: Install tools
      ansible.builtin.include_tasks:
        file: tasks/install-tools.yml

    - name: Install AWS CLI v2
      ansible.builtin.include_tasks:
        file: tasks/awscli.yml

    - name: Install Go
      ansible.builtin.include_tasks:
        file: tasks/go.yml
      # ignore_errors: true

    - name: Install Terraform
      ansible.builtin.include_tasks:
        file: tasks/terraform.yml

    - name: Install NodeJS
      ansible.builtin.include_tasks:
        file: tasks/nodejs.yml

    # - name: Install brave
    #   ansible.builtin.include_tasks:
    #     file: tasks/brave.yml
    # NOT TESTED

    - name: Install signal
      ansible.builtin.include_tasks:
        file: tasks/signal.yml

    - name: Install spotify
      ansible.builtin.include_tasks:
        file: tasks/spotify.yml

    - name: Install flatpak apps
      ansible.builtin.include_tasks:
        file: tasks/flathub.yml

    - name: Configure Git
      ansible.builtin.include_tasks:
        file: tasks/git.yml

    - name: Configure SSH for GitHub
      ansible.builtin.include_tasks:
        file: tasks/ssh.yml

    - name: Print SSH key
      ansible.builtin.debug:
        msg:
          - "{{ ssh_key_pub }}"
          - "Add the SSH public key to GitHub & reload your terminal to use the installed tools."
      become: false
