---
- name: Setup my workstation
  hosts: localhost
  connection: local
  become: true
  vars:
    email: "62394512+maheshrjl@users.noreply.github.com"
    key_name: "gh"

  tasks:
    - name: Update & upgrade packages in Debian
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        autoremove: true
      when: ansible_os_family == "Debian"

    - name: Install packages
      ansible.builtin.package:
        name:
          - vim
          - git
          - curl
          - wget
          - htop
          - python3
          - python3-pip
          - xclip
          - tree

    - name: Create SSH directory
      ansible.builtin.file:
        path: "~/.ssh"
        state: directory
        mode: "0700"
      become: false

    - name: Generate SSH key
      community.crypto.openssh_keypair:
        path: "~/.ssh/{{ key_name }}"
        comment: "{{ email }}"
        type: ed25519
        force: false
      register: ssh_key
      become: false

    - name: Add SSH key to ssh agent
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        line: "eval $(ssh-agent) && ssh-add ~/.ssh/{{ key_name }}"
        create: true
        insertafter: EOF
        backup: true
      become: false

    # - name: Create a GPG key
    #   ansible.builtin.command: >
    #     gpg --batch --gen-key << EOF
    #     %no-protection
    #     Key-Type: RSA
    #     Key-Length: 4096
    #     Name-Real: Mahesh Rijal
    #     Name-Email: {{ email }}
    #     Expire-Date: 1y
    #     %commit
    #     %echo done
    #     EOF
    #   register: gpg_key
    #   become: false

    # - name: Print GPG key
    #   ansible.builtin.debug:
    #     msg: "{{ gpg_key.stdout }}"
    #   become: false

    - name: Print SSH key
      ansible.builtin.debug:
        msg: "{{ ssh_key.public_key }}"
      become: false
