---
- name: Install essential tools
  ansible.builtin.package:
    name:
      - curl
      - wget
      - unzip
      - vim
      - htop
      - build-essential
      - lsof
      - tar
      - jq
      - git
      - tree
      - bind9-dnsutils
      - tmux
      - gpg
      - net-tools
      - zip
      - vlc
    state: present
