---
- name: Install essential tools
  ansible.builtin.package:
    name:
      - curl
      - wget
      - unzip
      - vim
      - python3
      - python3-pip
      - htop
      - build-essential
      - lsof
      - tar
      - jq
      - git
      - tree
      - bind9-dnsutils
      - tmux
      - gpg
      - net-tools
      - zip
      - vlc
    state: present

- name: Upgrade pip
  ansible.builtin.pip:
    name: pip
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python3
