---
- name: Remove OLD PPA for Node.js
  become: true
  apt_repository:
    repo: "ppa:chris-lea/node.js"
    state: absent
    update_cache: true

- name: Add nodesource package signing key
  become: true
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add nodesource repository
  become: true
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_16.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: true

- name: Install Node.js
  become: true
  apt:
    name: nodejs
    state: present
    update_cache: true
