---
- name: Check if NVM is already installed
  ansible.builtin.stat:
    path: /home/{{ ansible_user_id }}/.nvm/nvm.sh
  register: nvm_installed
  become: false

- name: Download NVM install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh
    dest: /tmp/nvm-install.sh
    mode: '0755'
  become: false
  when: not nvm_installed.stat.exists

- name: Install NVM
  ansible.builtin.shell: |
      set -o pipefail
      bash /tmp/nvm-install.sh
  args:
    creates: /home/{{ ansible_user_id }}/.nvm/nvm.sh
    executable: /bin/bash
  become: false
  when: not nvm_installed.stat.exists

- name: Ensure NVM is loaded
  ansible.builtin.shell: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      nvm --version
  register: nvm_version
  changed_when: false
  become: false

- name: Check if Node.js is already installed via NVM
  ansible.builtin.shell: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      nvm ls --no-colors | grep -q 'lts/*'
  register: node_installed
  ignore_errors: true
  changed_when: false
  become: false

- name: Install latest LTS Node.js using NVM
  ansible.builtin.shell: |
      set -o pipefail
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      nvm install --lts
  args:
    executable: /bin/bash
  become: false
  when: node_installed.rc != 0
  changed_when: true

- name: Set default Node.js to latest LTS
  ansible.builtin.shell: |
      set -o pipefail
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      nvm alias default lts/*
  args:
    executable: /bin/bash
  become: false
  when: node_installed.rc != 0
  changed_when: true

- name: Print Node.js version
  ansible.builtin.shell: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      node --version
  register: node_version
  changed_when: false
  become: false

- name: Print Node.js version output
  ansible.builtin.debug:
    msg: "{{ node_version.stdout }}"
  become: false
