---
- name: Remove OLD PPA for Node.js
  become: true
  ansible.builtin.apt_repository:
    repo: "ppa:chris-lea/node.js"
    state: absent
    update_cache: true

- name: Add nodesource package signing key
  become: true
  ansible.builtin.apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    keyring: /etc/apt/trusted.gpg.d/nodesource.gpg
    state: present

- name: Add nodesource repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ node_version }} {{ ansible_distribution_release }} main"
    state: present
    update_cache: true

- name: Install Node.js {{ node_version }}}
  become: true
  ansible.builtin.apt:
    name: nodejs
    state: present
    update_cache: true
