---
- name: Remove OLD PPA for Node.js
  become: true
  ansible.builtin.apt_repository:
    repo: "ppa:chris-lea/node.js"
    state: absent
    update_cache: true

- name: Check if repo for node_{{ node_version }} exists
  ansible.builtin.shell: apt-cache policy | grep -i "nodesource.com/{{ node_version }}"
  register: repo_check
  changed_when: false
  failed_when: false
  ignore_errors: yes

- name: Add nodesource package signing key
  become: true
  ansible.builtin.apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    keyring: /etc/apt/trusted.gpg.d/nodesource.gpg
    state: present

- name: Remove existing Node.js installation
  become: true
  ansible.builtin.apt:
    name: nodejs
    state: absent
  when: repo_check.rc != 0 # Remove old version when repo is not found
  changed_when: repo_check.rc == 0

- name: Add nodesource repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ node_version }} {{ ansible_distribution_release }} main"
    state: present
    update_cache: true
  when: repo_check.rc != 0

- name: Install Node.js {{ node_version }}}
  become: true
  ansible.builtin.apt:
    name: nodejs
    state: present
    update_cache: true
  when: repo_check.rc != 0
  changed_when: repo_check.rc == 0
