---
- name: Download Signal GPG key
  ansible.builtin.get_url:
    url: https://updates.signal.org/desktop/apt/keys.asc
    dest: /tmp/signal-desktop-keyring.asc
    mode: '0644'
  when: not is_wsl

- name: Convert Signal GPG key to keyring
  ansible.builtin.command: >
    bash -o pipefail -c 'gpg --dearmor < /tmp/signal-desktop-keyring.asc > /tmp/signal-desktop-keyring.gpg'
  args:
    creates: /tmp/signal-desktop-keyring.gpg
  when: not is_wsl

- name: Move GPG key to /usr/share/keyrings
  ansible.builtin.copy:
    src: /tmp/signal-desktop-keyring.gpg
    dest: /usr/share/keyrings/signal-desktop-keyring.gpg
    remote_src: false
    owner: root
    group: root
    mode: '0644'
  when: not is_wsl

- name: Add Signal repository to apt sources
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main"
    state: present
    filename: signal-xenial
  when: not is_wsl

- name: Update APT package index
  ansible.builtin.apt:
    update_cache: true
  when: not is_wsl

- name: Install Signal Desktop
  ansible.builtin.apt:
    name: signal-desktop
    state: present
  when: not is_wsl
