- name: Create SSH directory
  ansible.builtin.file:
    path: "~/.ssh"
    state: directory
    mode: "0700"
  become: false

- name: Generate SSH key
  community.crypto.openssh_keypair:
    path: "~/.ssh/{{ key_name }}"
    comment: "{{ email }}"
    type: ed25519
    force: false
    mode: "0600"
  register: ssh_key
  become: false

- name: Add SSH key to ssh agent
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    mode: "0644"
    line: "eval $(ssh-agent) > /dev/null 2>&1 && ssh-add ~/.ssh/{{ key_name }} > /dev/null 2>&1"
    create: true
    insertafter: EOF
    backup: true
  become: false

- name: Lookup SSH key & store in variable
  ansible.builtin.set_fact:
    ssh_key_pub: "{{ lookup('file', '~/.ssh/{{ key_name }}.pub') }}"
  become: false
