---
- name: Add hashicorp GPG key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  when: ansible_os_family == "Debian"

- name: Add hashicorp repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    state: present
  when: ansible_os_family == "Debian"

- name: Install Terraform
  ansible.builtin.apt:
    name: terraform
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Enable autocomplete for Terraform
  ansible.builtin.lineinfile:
    path: /etc/profile
    line: 'complete -C "/usr/bin/terraform" terraform'
    create: true
    state: present
    mode: "0644"

- name: Verify Terraform installation
  ansible.builtin.command: "terraform version"
  register: terraform_version
  changed_when: false
  become: false

- name: Print Terraform version
  ansible.builtin.debug:
    msg: "{{ terraform_version.stdout }}"
