---
- name: Download Vivaldi browser deb package
  ansible.builtin.get_url:
    url: https://vivaldi.com/download/vivaldi-stable_amd64.deb
    dest: /tmp/vivaldi-stable_amd64.deb
    mode: '0644'
  when: not is_wsl

- name: Install Vivaldi browser
  ansible.builtin.apt:
    deb: /tmp/vivaldi-stable_amd64.deb
    state: present
  when: not is_wsl

- name: Remove downloaded Vivaldi deb package
  ansible.builtin.file:
    path: /tmp/vivaldi-stable_amd64.deb
    state: absent
  when: not is_wsl
